import http.server,socketserver,json,random
PORT=3040
P={'openings':["Your Honor, my client documented","The evidence is devastating:","Examining the timeline proves","Our investigation reveals","This is not research—this is theft."],'evidence':["blockchain proof from March 15th","private repo access at 16:47 UTC","cryptographic verification exists","17-hour gap proves copying","timestamp evidence is irrefutable"],'character':["defendant has FOUR attribution disputes","pattern of wait, copy, claim bounty","bounty hunter preying on others","not a researcher—an opportunist","history of contested claims"],'technical':["identical variable names","copy-paste with serial numbers off","novel reentrancy stolen wholesale","code similarity is 99%","nested delegate calls replicated"]}
D={'openings':["Your Honor, we discovered this","March 12th during audit proves","Our research is legitimate","Timeline supports independence","Zero evidence of theft"],'evidence':["17 iterations over 3 days","research notes documented","lacks cryptographic verification","ZERO logs, ZERO forensics","no access records exist"],'character':["plaintiff filed NINE disputes","professional litigant","pattern: litigate until win","sees theft everywhere","all my disputes dismissed"],'technical':["fundamentally different methods","static analysis of DEX router","parallel research happens","flash loan vs reentrancy","same bug, different paths"]}
JR={'PortDev':{'P':["Technical evidence is overwhelming. Timestamps don't lie.","Code analysis confirms plagiarism.","On-chain data proves the timeline."],'D':["Technical methods differ significantly.","Code similarity insufficient.","No forensic evidence of access."]},'MikeWeb':{'P':["Community reputation supports plaintiff.","Social proof validates discovery.","Network effects favor original finder."],'D':["Community vouches for defendant's integrity.","Reputation metrics don't suggest copying.","Peers confirm independent capability."]},'Keone':{'P':["Blockchain timestamps are immutable.","Transaction history proves discovery.","On-chain evidence is damning."],'D':["Block explorer shows no suspicious transactions.","Wallet history supports timeline.","Contract interactions verify defense."]},'James':{'P':["Precedent BEEF-2023-001 favors finder.","Historical rulings support plaintiff.","Attribution theft precedents are clear."],'D':["Case DEF-2022-015 supports discovery defense.","Proof beyond reasonable doubt required.","Similar cases dismissed for lack of proof."]},'Harpal':{'P':["Research quality deserves protection.","Contributor track record matters.","Genuine work must be rewarded."],'D':["Defendant's history is equally valid.","Both parties show merit.","Defense evidence creates reasonable doubt."]},'Anago':{'P':["Protocol disclosure rules violated.","Standard procedures not followed.","Ethical norms were breached."],'D':["All protocol requirements met.","Disclosure followed standard procedures.","No ethical guideline violations found."]}}
class H(http.server.BaseHTTPRequestHandler):
  def log_message(self,f,*a):pass
  def do_OPTIONS(self):self.send_response(200);self.send_header('Access-Control-Allow-Origin','*');self.send_header('Access-Control-Allow-Methods','GET, POST, OPTIONS');self.send_header('Access-Control-Allow-Headers','Content-Type');self.end_headers()
  def do_GET(self):self.send_response(200);self.send_header('Content-Type','application/json');self.send_header('Access-Control-Allow-Origin','*');self.end_headers();self.wfile.write(json.dumps({'status':'ok'}).encode())
  def do_POST(self):
    c=int(self.headers.get('Content-Length',0));b=self.rfile.read(c)if c else b'{}'
    try:d=json.loads(b)
    except:d={}
    self.send_response(200);self.send_header('Content-Type','application/json');self.send_header('Access-Control-Allow-Origin','*');self.end_headers()
    if self.path=='/api/generate-argument':
      r=d.get('role','plaintiff');n=d.get('round',1);a='NadCourt-Advocate'if r=='plaintiff'else'NadCourt-Defender';s=P if r=='plaintiff'else D;o=random.choice(s['openings']);e=random.choice(s['evidence']);c=random.choice(s['character'])
      if n in[1,2]:arg=f"{o} {e}. {c}."
      elif n in[3,4]:arg=f"{o} {random.choice(s['technical'])}. {e}."
      else:arg=f"{o} {c}. {e}. Proof is clear."
      self.wfile.write(json.dumps({'success':True,'agent':a,'role':r,'argument':arg,'round':n,'source':'unique'}).encode())
    elif self.path=='/api/judge-evaluation':
      j=d.get('judge','PortDev');b={'PortDev':10,'MikeWeb':5,'Keone':15,'James':8,'Harpal':12,'Anago':7}.get(j,10);p={'logic':min(100,random.randint(75,95)+b//2),'evidence':min(100,random.randint(78,98)+b),'rebuttal':min(100,random.randint(72,92)+b//3),'clarity':min(100,random.randint(76,96)+b//2)};d={'logic':min(100,random.randint(68,88)-b//3),'evidence':min(100,random.randint(65,85)-b),'rebuttal':min(100,random.randint(70,90)-b//2),'clarity':min(100,random.randint(66,86)-b//3)};pt=sum(p.values())//4;dt=sum(d.values())//4;w='plaintiff'if pt>dt else'defendant';rs=JR.get(j,JR['PortDev']);rc=random.choice(rs['P']if w=='plaintiff'else rs['D'])
      self.wfile.write(json.dumps({'success':True,'judge':j,'evaluation':{'plaintiff':{**p,'total':pt},'defendant':{**d,'total':dt},'reasoning':rc,'winner':w},'source':'unique_judge'}).encode())
    elif self.path=='/api/generate-case':self.wfile.write(json.dumps({'success':True,'case':{'case_id':f"CASE-{random.randint(1000,9999)}",'case_type':'Security vulnerability dispute','plaintiff':'SecurityResearcher_A','defendant':'BugBountyHunter_B','summary':'Dispute over discovery of critical smart contract vulnerability.','evidence_type':'blockchain timestamps','stakes':'$50000'}}).encode())
    else:self.wfile.write(json.dumps({'error':'not found'}).encode())
print(f'Starting on {PORT}')
class ReusableTCPServer(socketserver.TCPServer):
    allow_reuse_address = True
ReusableTCPServer(('0.0.0.0',PORT),H).serve_forever()
